Repository tosinoni/CapstoneSystem, pull requests merged in 2018-04, with the labels that each got.

#89 [Issue #87] finalized the apply and cancel button
  bower.json
  src/main/java/com/carleton/CapstoneSystem/Controllers/ProjectController.java
  src/main/java/com/carleton/CapstoneSystem/restfulControllers/ProjectResource.java
  src/main/resources/static/index.html
  src/main/resources/static/js/projects/project-controller.js
  src/main/resources/static/js/services/Project.js
  src/main/resources/static/js/services/SwalService.js
  src/main/resources/static/views/projects/project.html
Labels: Feature

#91 [Issue #90] finished implementing add students to project
  src/main/java/com/carleton/CapstoneSystem/Controllers/ProjectController.java
  src/main/java/com/carleton/CapstoneSystem/DTO/ProjectDTO.java
  src/main/java/com/carleton/CapstoneSystem/models/Project.java
  src/main/java/com/carleton/CapstoneSystem/models/Student.java
  src/main/java/com/carleton/CapstoneSystem/restfulControllers/ProjectResource.java
  src/main/java/com/carleton/CapstoneSystem/utils/ProjectErrorMessages.java
  src/main/resources/static/js/projects/project-controller.js
  src/main/resources/static/js/services/Project.js
  src/main/resources/static/js/welcome/welcome-controller.js
  src/main/resources/static/views/projects/project.html
  src/main/resources/static/views/welcome/welcome.html
  src/test/java/com/carleton/CapstoneSystem/models/ProjectTest.java
Labels: Feature

#94 [Issue #93] finished implementing edit project
  src/main/java/com/carleton/CapstoneSystem/Controllers/ProjectController.java
  src/main/java/com/carleton/CapstoneSystem/DTO/ProfessorDTO.java
  src/main/java/com/carleton/CapstoneSystem/DTO/ProjectDTO.java
  src/main/java/com/carleton/CapstoneSystem/restfulControllers/ProjectResource.java
  src/main/java/com/carleton/CapstoneSystem/utils/ProjectErrorMessages.java
  src/main/java/com/carleton/CapstoneSystem/utils/Util.java
  src/main/resources/static/index.html
  src/main/resources/static/js/directives/kapi-projects-modal/kapi-projects-modal.html
  src/main/resources/static/js/directives/kapi-projects-modal/kapi-projects-modal.js
  src/main/resources/static/js/projects/project-controller.js
  src/main/resources/static/js/projects/projects-controller.js
  src/main/resources/static/js/services/Project.js
  src/main/resources/static/views/projects/project.html
  src/main/resources/static/views/projects/projects.html
Labels: Feature

#96 [Issue #93] finished implementing archive project
  src/main/java/com/carleton/CapstoneSystem/Controllers/ProjectController.java
  src/main/java/com/carleton/CapstoneSystem/DTO/ProfessorDTO.java
  src/main/java/com/carleton/CapstoneSystem/DTO/StudentDTO.java
  src/main/java/com/carleton/CapstoneSystem/restfulControllers/ProjectResource.java
  src/main/resources/static/js/directives/kapi-projects-table/kapi-projects-table.html
  src/main/resources/static/js/projects/project-controller.js
  src/main/resources/static/js/services/Project.js
  src/main/resources/static/js/services/SwalService.js
  src/main/resources/static/views/projects/project.html
Labels: Feature

#98 [Issue #97] finished implementing delete project
  src/main/java/com/carleton/CapstoneSystem/Controllers/ProjectController.java
  src/main/java/com/carleton/CapstoneSystem/restfulControllers/ProjectResource.java
  src/main/java/com/carleton/CapstoneSystem/utils/ProjectErrorMessages.java
  src/main/resources/static/js/projects/project-controller.js
  src/main/resources/static/js/services/Project.js
  src/main/resources/static/js/services/SwalService.js
  src/main/resources/static/views/projects/project.html
Labels: Feature

#102 [Issue #101] Updated creation of submissions for all users
  src/main/java/com/carleton/CapstoneSystem/Controllers/ProjectController.java
  src/main/java/com/carleton/CapstoneSystem/restfulControllers/ProjectResource.java
  src/main/resources/static/index.html
  src/main/resources/static/js/projects/project-controller.js
  src/main/resources/static/js/projects/submissions-controller.js
  src/main/resources/static/js/services/Project.js
  src/main/resources/static/views/projects/project.html
  src/main/resources/static/views/projects/submissions.html
Labels: Feature, enhancement

#107 Update submissions page
  src/main/resources/static/js/projects/project-controller.js
  src/main/resources/static/js/projects/submissions-controller.js
  src/main/resources/static/views/projects/project.html
  src/main/resources/static/views/projects/submissions.html
Labels: enhancement

#104 [Issue #103] Updated scheduling availability page
  src/main/resources/static/index.html
  src/main/resources/static/views/projects/schedule.html
Labels: Feature

#109 [Issue #108] finished implementing add deliverable for professors
  bower.json
  src/main/java/com/carleton/CapstoneSystem/Controllers/ProjectController.java
  src/main/java/com/carleton/CapstoneSystem/Controllers/SubmissionController.java
  src/main/java/com/carleton/CapstoneSystem/DTO/SubmissionDTO.java
  src/main/java/com/carleton/CapstoneSystem/models/Project.java
  src/main/java/com/carleton/CapstoneSystem/models/Submission.java
  src/main/java/com/carleton/CapstoneSystem/repositories/SubmissionRepository.java
  src/main/java/com/carleton/CapstoneSystem/restfulControllers/ProjectResource.java
  src/main/java/com/carleton/CapstoneSystem/restfulControllers/SubmissionResource.java
  src/main/java/com/carleton/CapstoneSystem/utils/SubmissionErrorMessages.java
  src/main/resources/static/index.html
  src/main/resources/static/js/projects/submissions-controller.js
  src/main/resources/static/js/services/Submission.js
  src/main/resources/static/views/projects/submissions.html
  src/test/java/com/carleton/CapstoneSystem/models/ProjectTest.java
  src/test/java/com/carleton/CapstoneSystem/models/SubmissionTest.java
Labels: Feature

#111 [Issue #108] finished implementing add deliverable for studnets
  bower.json
  src/main/java/com/carleton/CapstoneSystem/Controllers/SubmissionController.java
  src/main/java/com/carleton/CapstoneSystem/DTO/SubmissionDTO.java
  src/main/java/com/carleton/CapstoneSystem/models/Grade.java
  src/main/java/com/carleton/CapstoneSystem/models/Submission.java
  src/main/java/com/carleton/CapstoneSystem/restfulControllers/SubmissionResource.java
  src/main/java/com/carleton/CapstoneSystem/utils/SubmissionErrorMessages.java
  src/main/resources/static/index.html
  src/main/resources/static/js/app.js
  src/main/resources/static/js/projects/submissions-controller.js
  src/main/resources/static/views/projects/submissions.html
  src/test/java/com/carleton/CapstoneSystem/models/SubmissionTest.java
Labels: Feature
